import Layout from "../../components/Layout";
import PageIntroduction from "../../components/PageIntroduction";
import { PageWrapper } from "../../components/PageWrapper";
import NextChapter from "../../components/Navigation/NextChapter";
import CaseStudyWrapper from "../../components/CaseStudy/CaseStudyWrapper";
import ContentContainer from "../../components/ContentContainer";
import Citation from "../../components/Bibliography/Citation";

const DevelopPage = () => (
  <Layout title="Develop | RA Experience Design">
    <PageWrapper>
      <PageIntroduction>
        <h1>Develop</h1>
        <p>
          After successfully defining what the right problem is to solve, it is
          time to embark on an ideation journey. Ideation is the process of{" "}
          <em>generating a broad set of ideas</em> to solve a previously defined
          problem, with no attempt to judge or evaluate them mid-session{" "}
          <Citation id="nngroupIdeation" />.
        </p>
      </PageIntroduction>
    </PageWrapper>
    <PageWrapper>
      <ContentContainer>
        <h2>Ideation</h2>
        <p>
          The focus during an ideation session is on improving the user
          experience. By investigating multiple solutions in parallel, we have a
          better chance of discovering the optimal solution, rather than merely
          the first that pops to mind. A critical mechanic of an ideation
          session is that all judgment is postponed until after{" "}
          <Citation id="nngroupIdeation" />.
        </p>
        <h3>Early ideas are Fragile</h3>
        <p>
          Young ideas are usually unfinished, and as a result, it's easy to
          concentrate on its flaws rather than its beauty. This is why it's so
          important to remember not to judge ideas in the middle of ideation.
          Dugosh et al. <Citation id="cognitiveStimulation" hideAuthor />{" "}
          determined that a subsequent incubation session would be useful.
          Designers can use this time to reflect on the ideas that have been
          shared, to generate additional ideas. This also leads us to another
          important factor, the power of collaboration.
        </p>
        <h3>Collaboration</h3>
        <p>
          The same paper suggests there are benefits to the exposure to others'
          ideas in brainstorming sessions. Even when designers are generating
          their own ideas, it's possible to process the ideas generated by
          someone else simultaneously. In essence, that suggests collaboration
          spurs more and more diverse ideas.{" "}
        </p>
        <h3>Volume and Diversity</h3>
        <p>
          The metrics of for measuring ideation effectiveness is defined by the
          volume and differentiation of the pool of ideas{" "}
          <Citation id="ideationMetrics" />. The quality of design space
          exploration is a key component to good user experience{" "}
          <Citation id="nngroupParallel" />.
        </p>
        <h3>Scale Back</h3>
        <p>
          It is integral for effective ideation to set aside any real-world
          constraints such as technical feasibility or business viability. At
          this stage of the design process, no idea is too farfetched.{" "}
        </p>
        <blockquote>
          <p>
            “You want to be able to project yourself 20 years into the future,
            and then think backwards from there. Trust yourself—20 years is a
            long time; it’s ok if your ideas about it seem pretty radical.”
          </p>
          <ul>
            <li>
              Sam Altman <Citation id="samAltman" hideAuthor />
            </li>
          </ul>
        </blockquote>
        <p>
          It's easier to scale back a crazy idea that addresses a true user need
          than to try to make a mundane idea desirable{" "}
          <Citation id="nngroupIdeation" />.
        </p>
        <h2>Evaluate</h2>
        <p>
          While it's now clear we don't want to put down ideas too early, at
          some point we'll have to decide which ones to toss, and which ones to
          move forward with. That's where evaluation comes into play. Design
          thinking generally looks at evaluating <em>feasibility</em>,{" "}
          <em>desirability</em> and <em>viability</em>{" "}
          <Citation id="designThinkingIDEO" />, integrating human needs with
          business needs. When we zoom in on the people's needs we find research
          that that categorizes product experience into three levels.
        </p>
        <h3>Levels of experiencing product</h3>
        <p>
          Pieter Desmet & Paul Hekkert <Citation id="experienceDesmet" />{" "}
          introduce a framework to assess product experience. The three levels
          of product experience they define are aesthetic pleasure, attribution
          of meaning and emotional response.
        </p>
        <p>
          At the aesthetic level, they consider a product’s capacity to delight
          one or more senses. Products can be beautiful to look at or pleasant
          to touch, these micro-experiences all add up to the total experience
          users have with the product. At the level of meaning, cognition comes
          into play. This defines how users attach personal or symbolic
          significance to the products they use. At the emotional level, they
          refer to the emotional response we have when interacting with products
          (emotion as in everyday language like love and disgust). These lenses
          can be considered to ensure all bases are covered by our evaluation
          process.{" "}
        </p>
      </ContentContainer>
    </PageWrapper>
    <CaseStudyWrapper>
      <ContentContainer>
        <p>
          Our ideation sessions were mostly done synchronously as a group. We
          started the process by clearing our head, writing down our initial
          thoughts (they're generally not the best ideas).{" "}
        </p>
        <h3>Ideation</h3>
        <p>
          There are <em>many</em> ideation tools we could've used, but our
          journey was inspired by The Pop-up Agency's variation of Crazy 8's.
          Their method provides several prompts to encourage diverse ideas,
          like; <em>“Idea your granny can understand”</em>,{" "}
          <em>“Zero budget idea”</em> and <em>“Unlimited budget idea”</em>.
        </p>
        <h3>Evaluation</h3>
        <p>
          Our evaluation came quite naturally, we personally filtered the ideas
          we personally weren't fond of. That cut our idea pool from around 30
          to roughly 12. We quickly saw some overlapping ideas, which we
          combined into two larger ideas:
        </p>
        <ul>
          <li>
            Shoes sold at a premium that become cheaper as they're being worn
            often
          </li>
          <li>A digital wardrobe with old (no longer for sale) collections </li>
        </ul>
      </ContentContainer>
    </CaseStudyWrapper>
    <NextChapter title="Deliver" index={4} />
  </Layout>
);

export default DevelopPage;
